### ISSUE TITLE
abort-current-inline-script can't block ad reinsertion

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/Scriptlets#188]
Related feedback: https://github.com/uBlockOrigin/uAssets/issues/9701#issuecomment-1026703999
A filter supposed to work (but not): `duplichecker.com#%#//scriptlet("abort-current-inline-script", "setTimeout", "pagead2.googlesyndication.com")`
A working filter: `duplichecker.com#%#//scriptlet("abort-on-property-read", "setTimeout")`
Chrome Ext. v3.6.17

**Comment by AdamWr** [comment]
If I'm not wrong, it should works if you use `jQuery` instead of `$`, for example:
```
duplichecker.com#%#//scriptlet("abort-current-inline-script", "jQuery", "pagead2.googlesyndication.com")
```

**Comment by Yuki2718** [comment]
Yes, that works. Can you replace `duplichecker.com#%#//scriptlet("abort-current-inline-script", "$", "pagead2.googlesyndication.com")` with that? Probably an old filter by https://github.com/AdguardTeam/AdguardFilters/issues/33446 should also be removed. I opend this issue because the filter works on uBO.

**Comment by AdamWr** [comment]
As far as I understand, it may works in uBO, because there is generic rule to redirect `pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` and `duplichecker.com##+js(no-xhr-if, ads)`.
If you add:
```
duplichecker.com#@#+js(no-xhr-if, ads)
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xmlhttprequest,redirect-rule=googlesyndication_adsbygoogle.js:5,badfilter
```
to "My filter" then `abort-current-inline-script` will not works.

If I understand correctly, it happens, because they are checking if `pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` is blocked.
```js
$.get('https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js').then(function (data, textStatus, jqXHR) {
  if (data == "") {
    bb();
  } else {
    ajo_thokdo();
  }
}).catch(error => {
  bb();
});
```
If so, then they run `bb` function which just display ads.
If `adsbygoogle.js` is not blocked then they run `ajo_thokdo` function which is using `setTimeout` and in this case `abort-current-inline-script` will abort it.

**Comment by Yuki2718** [comment]
Okay, thanks for taking time to investigate which I should have done.
