### ISSUE TITLE
Improve translation into uBo file for `remove-class` / `remove-attr`

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/Scriptlets#245]
As I said in #152 nice will be implement translation AG syntax to uBo syntax with injection parameter when AG based on default [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).

So uBo added parameter but default run scriptlet once and sometimes run before class or attribute exist.

<ul> <li>

So remove-class should have visible `stay`:

`is.fi#%#//scriptlet('remove-class', 'stuck', '.placeholder > .sticky-container.stuck')`

➡️ 

`is.fi##+js(remove-class, stuck, .placeholder > .sticky-container.stuck,`<b>`stay)`</b>

<li>

And remove-attr should have visible `asap stay`:

`musixmatch.com#%#//scriptlet('remove-attr', 'style|oncontextmenu', 'body')`

➡️ 

`musixmatch.com##+js(remove-attr, style|oncontextmenu, body,`<b>` asap stay)`</b>

At `musixmatch.com` we can see needed `stay` or `completed` due attribs was added very late on page - without parameter with uBo selection on page will be still locked.

</ul>

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersCompiler/issues/124

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersCompiler/issues/124

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersCompiler/issues/124 https://github.com/AdguardTeam/Scriptlets/issues/152 https://github.com/AdguardTeam/Scriptlets/issues/245

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersCompiler/issues/124 https://github.com/AdguardTeam/Scriptlets/issues/152 https://github.com/AdguardTeam/Scriptlets/issues/245

**Comment by krystian3w** [comment]
I fixed mistake in description, `rc` in uBo still wait for real examples to implement `asap` tribe.

**Comment by krystian3w** [comment]
small changes in the future may occur: https://github.com/gorhill/uBlock/commit/992255e9937f81b5dd58524caa2ceeaeb29efb14

Further I don't know in which repository to open the notification of operator deployment, I guess ExtendedCSS?

**Comment by ameshkov** [comment]
Yeah, this is for ExtCSS. CC @slavaleleka 

Also, I don't think we'll do it the same way @gorhill does. This whole approach with `:remove()`, `:style()` and others is semantically incorrect, CSS selectors are supposed to select elements and not modify what they select.

We'll implement it via style properties, i.e.: `selector { remove-attr: attr-name }`. uBO rules will be converted to our syntax automatically so filters maintainers will not feel the difference.

**Comment by gorhill** [comment]
> CSS selectors are supposed to select elements and not modify what they select

Although for the time being I decided to not do this, `remove-attr()` and `remove-class()` could very well also be passthru action operators, so that self-imposed restriction would prevent this.

**Comment by ameshkov** [comment]
@gorhill is there a real use case for that? Dealing with something like that would be tricky:`[data=attr]:remove-attr(data) > div`.

**Comment by gorhill** [comment]
I like to have the flexibility for this in the future. For instance, I have considered since a long time now to have a sort of `hide()` operator to avoid having to use two or more cosmetic filters. Consider the following case (which is a suggested solution in [our FAQ](https://www.reddit.com/r/uBlockOrigin/wiki/solutions)):

    twitter.com##[aria-label="Timeline: Conversation"] h2>div>span:has-text(/^More Tweets$/):upward([style^="transform"])
    twitter.com##[aria-label="Timeline: Conversation"] h2>div>span:has-text(/^More Tweets$/):upward([style^="transform"]) ~ div

Could become:

    twitter.com##[aria-label="Timeline: Conversation"] h2>div>span:has-text(/^More Tweets$/):upward([style^="transform"]):hide() ~ div

Such cases which are meant to target self and siblings (through `+` or `~`) is not that uncommon, and having a solution to do all this in one pass not only make filter maintenance easier, but also more efficient.

Another solution to the above case could maybe also be done with a sort of `:select()` operator, which would add the nodes at that point to the final nodeset -- in which case this wouldn't be an action operator:

    twitter.com##[aria-label="Timeline: Conversation"] h2>div>span:has-text(/^More Tweets$/):upward([style^="transform"]):select() ~ div

**Comment by ameshkov** [comment]
> having a solution to do all this in one pass not only make filter maintenance easier, but also more efficient

This is a good example, but does it justify generally allowing having multiple actions in a single cosmetic rule? Here are some practical things that I don't like about combining multiple actions in a single rule:

1. It will hurt readability even more. It's not that filter rules are simple to comprehend now, sticking everything in a single line is generally not a great recipe for that. But if multiple actions are allowed, a maintainer will have more to untangle. Your example is rather easy to understand, imagine if there are several different action pseudos somewhere in the middle one would need to be careful not to miss them.
2. It will be harder to detect redundant rules. With "narrow" rules it is easier to automatically detect that a rule is now redundant -> remove it. When a rule does many things at the same time, it may become "partly" redundant.
3. It will be confusing since `:remove-*` actions in the middle change DOM and it's unclear how the selector should behave after that: `#banner:remove() + h1`.

So yes, a single rule will be more efficient, but I don't think it will make maintenance easier.

> Another solution to the above case could maybe also be done with a sort of :select() operator, which would add the nodes at that point to the final nodeset -- in which case this wouldn't be an action operator:

Sounds interesting. Solves №2 and №3. Does not help readability too much since we'll be sticking more stuff in a single rule, but not too drastic. I've quickly skimmed through AG Base filter and there are a few cases where with `:select()` we could replace multiple rules with one.

Actually, after thinking a bit more, it can potentially be more powerful than `:has()`. I'd even suggest changing its definition a little to add more flexibility, let it not just add to the final nodeset, but redefine what's selected. I.e. when it is present in the selector, only what's marked with `:select` gets to the final nodeset.

In this case these two selectors will select identical nodes, but the second one seems more straightforward and easier to understand.

```adblock
#?#div:has(> h1 > p)
```

```adblock
#?#div:select() > h1 > p
```
