### ISSUE TITLE
Add new scriptlet — 'trusted-set-attr'

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/Scriptlets#281]
Original issue: https://github.com/AdguardTeam/Scriptlets/issues/106

**Comment by TEMP-ACCOUNT-m4C5gRm32s3Z** [comment]
I don't want to be _that person_ but is Adguard going to implement this?
While set-attr I see it mostly about 'fixing the web' rather than adblocking it would be great to have it available in Adguard and be able to set any value we want.

For example, many input elements don't have the `autocomplete="off"` which means you will get suggestions in other sites or even synchronized across devices, only because the input share the same 'name', this means Inputs are security and privacy nightmare in some cases, doesn't necessarily means you want to turn them off completely, but don't let some websites 'record' autofill data like that.
So if Adguard allowed to fix that issue some web developers don't care about, even if it is as simple as adding that attribute, would be great.

Also this could easily tweak links to be opened in self or new tab, rather than be dependent on what the web developer implemented.

I know Adguard will care about security risks, but freedom of internet is also important, and being able to fix bad web developer decisions is always a plus, even if that requires to fix the web for and by ourself, it would be great.

The scriptlet is already there, and implement it 'trusted' would be great, rather than expanding set-attr _trusted_ values, to every possibility. Looking at the original issue, it's been more than 3 years since it was mentioned and this issue is a year old already.

So I hope this will get implemented soon, eventually, someday, some time in my lifetime.
