### ISSUE TITLE
Fix set-constant — no value override

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/Scriptlets#330]
**website**: 
https://www.nivod4.tv/
**rules**:
```
nivod5.tv,nivod4.tv#%#//scriptlet('set-constant', 'pageData.__banners.0.commercial.mediaUrl', '')
nivod5.tv,nivod4.tv#%#//scriptlet('set-constant', 'pageData.__banners.0.commercial.jumpUrl', '')
nivod5.tv,nivod4.tv#%#//scriptlet('set-constant', 'pageData.__banners.0.commercial.title', '')
```
**Expected behaviour**: 
The first ad banner and its text is hidden
**Current behaviour**:
The banner is not hidden

Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/153658

**Comment by AdamWr** [comment]
Some additional information which maybe will be useful or maybe not 🙃 
I'm not sure if I understand correctly, but it looks like that firstly there is (just example):
<details><summary>Code:</summary>

```js
window.pageData = {
  __banners: [{
    commercial: {
      mediaUrl: "test"
    }
  }, {
    commercial: {
      mediaUrl: "test"
    }
  }]
};
```

</details>

then it's changed to:
<details><summary>Code:</summary>

```js
window.pageData.__banners = [{
  commercial: {
    mediaUrl: "test"
  }
}, {
  commercial: {
    mediaUrl: "test"
  }
}];
```

</details>

and it looks like that it overrides a value set by `set-constant` scriptlet.

Demo page - https://jsfiddle.net/a5oL2hpd/
<details><summary>Code:</summary>

```html
<script>
window.pageData = {
  __banners: [{
    commercial: {
      mediaUrl: "test"
    }
  }, {
    commercial: {
      mediaUrl: "test"
    }
  }]
};
console.debug('test1:', pageData.__banners[0].commercial.mediaUrl);
setTimeout(() => {
  window.pageData.__banners = [{
    commercial: {
      mediaUrl: "test"
    }
  }, {
    commercial: {
      mediaUrl: "test"
    }
  }];
  console.debug('test2:', pageData.__banners[0].commercial.mediaUrl);
}, 2000);
</script>
```

</details>

Rule:
```adblock
fiddle.jshell.net#%#//scriptlet('set-constant', 'pageData.__banners.0.commercial.mediaUrl', '')
```

On demo page, value of `pageData.__banners[0].commercial.mediaUrl` is displayed in the browser console.
With scriptlet, it firstly shows `test1: ` (it's correct) and then after 2 seconds `test2: test` and it's not correct, because it has been changed.

With `AG_defineProperty`:
```adblock
fiddle.jshell.net#%#AG_defineProperty('pageData.__banners.0.commercial.mediaUrl', { value: ''});
```
it works correctly and value is not overridden.

Maybe related to - https://github.com/AdguardTeam/Scriptlets/issues/65#issuecomment-676209753, and if so, then perhaps we could add a scriptlet which will not allow for overriding value, like in case of `AG_defineProperty`.

**Comment by AdamWr** [comment]
Another example:
Rule:
```adblock
fiddle.jshell.net#%#//scriptlet('set-constant', 'test.prototype.abc.qwerty', 'false')
```
Test page - https://jsfiddle.net/416bvhzu/

<details><summary>Code:</summary>

```html
<script>
window.test = function () {};
test.prototype = { whatever: 1 }; // if this is commented out scriptlet works correctly
test.prototype.abc = {
    qwerty: true
};
console.debug('test.prototype.abc.qwerty:', test.prototype.abc.qwerty);
</script>
```

</details>

`test.prototype.abc.qwerty` should be set to `false` by scriptlet, but it looks like if `test.prototype` is changed, then `test.prototype.abc.qwerty` is not overridden.
