### ISSUE TITLE
Escape commas in the params during conversion to ubo rules

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/Scriptlets#343]
https://github.com/AdguardTeam/FiltersCompiler/issues/185

**Comment by gorhill** [comment]
Starting with uBO 1.51.0, it is not necessary to escape commas if quotes are used around the parameters, it's ok to provide the parameters as they are declared in AdGuard. The only conversion needed might be the scriptlet name, but in such case it's best to just bring this to my attention so that I can add an alias on uBO's side.
