### ISSUE TITLE
Add new scriptlet — 'json-prune-fetch-response'

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/Scriptlets#361]
https://github.com/gorhill/uBlock/commit/749cec0f095f659d6c0b90eb89b729e9deb07c87

**Comment by Yuki2718** [comment]
`[youtube.com##+js(json-prune-fetch-response](http://youtube.com/##+js(json-prune-fetch-response), playerResponse.adPlacements playerResponse.playerAds playerResponse.adSlots adPlacements playerAds adSlots, , /playlist\?list=|player\?|watch\?v=/)` causes detection on uBO as uBO expect `propsToMatch` like `www.youtube.com##+js(json-prune-fetch-response, playerResponse.adPlacements playerResponse.playerAds playerResponse.adSlots adPlacements playerAds adSlots, , propsToMatch, player?)`. Unlike other compatibility issues I have reported, this can't be trivially fixed in FiltersCompiler because in AG implementation the position may not always be `propsToMatch`. Can you consider about this, as this will cause issues like this in the long run?
