### ISSUE TITLE
Fix 'log-on-stack-trace' — player is broken on deltabit.co

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/Scriptlets#384]
AdGuard for Chrome 4.2.228

### Steps to reproduce

1. Add `deltabit.co#%#//scriptlet('log-on-stack-trace', 'document.createElement')` to user rules
2. Open https://deltabit.co/52tiyuhsq52y with Italian VPN

### Actual behavior

The player is broken

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/Scriptlets/assets/8361299/ecc3619e-f5a0-48a5-b0ad-5a36741c907b)

</details>

Reported by @ghajini

**Comment by AdamWr** [comment]
Another steps to reproduce:
1. Add this rule:
```adblock
fiddle.jshell.net#%#//scriptlet('log-on-stack-trace', 'document.createElement')
```
2. Go to - `https://jsfiddle.net/eacwL8gz/`

<details><summary>Code:</summary>

```js
(()=> {
    const re = /(\w+)\s(\w+)/;
    const str = 'div a';
    str.replace(re, '$2, $1');
    document.createElement(RegExp.$1);
    console.log(`RegExp.$1: ${RegExp.$1}`);
    alert(`RegExp.$1: ${RegExp.$1}`);
})();
```

</details>

Alert `RegExp.$1: div` should be displayed, but there is an error:
```
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('') is not a valid name.
```
As far as I understand, the problem is that `RegExp.$1` is changed by scriptlet and it causes error.
