### ISSUE TITLE
Improve prevent-fab-3.2.0

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/Scriptlets#39]
https://github.com/AdguardTeam/AdguardFilters/issues/38930

Scriptlet prevent-fab-3.2.0 causes detection.

I temporarly excluded the domain from this rule.

**Comment by AdamWr** [comment]
One more issue with `prevent-fab-3.2.0` is that it doesn't work in this case - https://github.com/AdguardTeam/AdguardFilters/issues/39641

Checked with this rule:
`incredibox.com#%#//scriptlet("prevent-fab-3.2.0")`
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/64031940-c20a0b00-cb49-11e9-83b6-87c3a578174e.png)

</details>

With "old" JS rule it works fine.
```
incredibox.com#%#(function() { var noopfn = function() {;}; var Fab = function() {}; Fab.prototype.check = noopfn; Fab.prototype.clearEvent = noopfn;  Fab.prototype.emitEvent = noopfn; Fab.prototype.on = function(a, b) { if ( !a ) { b(); } return this; }; Fab.prototype.onDetected = function() {  return this; }; Fab.prototype.onNotDetected = function(a) { a(); return this; }; Fab.prototype.setOption = noopfn; var fab = new Fab(),  getSetFab = { get: function() { return Fab; }, set: function() {} }, getsetfab = { get: function() { return fab; }, set: function() {} }; if ( window.hasOwnProperty('FuckAdBlock') ) { window.FuckAdBlock = Fab; } else { Object.defineProperty(window, 'FuckAdBlock', getSetFab); } if ( window.hasOwnProperty('BlockAdBlock') ) { window.BlockAdBlock = Fab; } else {Object.defineProperty(window, 'BlockAdBlock', getSetFab); } if ( window.hasOwnProperty('SniffAdBlock') ) { window.SniffAdBlock = Fab; } else { Object.defineProperty(window, 'SniffAdBlock', getSetFab); } if ( window.hasOwnProperty('fuckAdBlock') ) { window.fuckAdBlock = fab; } else { Object.defineProperty(window, 'fuckAdBlock', getsetfab); } if ( window.hasOwnProperty('blockAdBlock') ) { window.blockAdBlock = fab; } else { Object.defineProperty(window, 'blockAdBlock', getsetfab); } if ( window.hasOwnProperty('sniffAdBlock') ) { window.sniffAdBlock = fab; } else { Object.defineProperty(window, 'sniffAdBlock', getsetfab); } })();
```

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/64032118-12816880-cb4a-11e9-896d-cf253fd3d904.png)

</details>

**Comment by slavaleleka** [comment]
@AdguardTeam/filters-maintainers 
`prevent-fab-3.2.0` is going to be updated as equal analog of [uBO's nofab.js](https://github.com/gorhill/uBlock/wiki/Resources-Library#nofabjs-) (for full compatibility so it will cover case with sniffAdBlock)

but it will not be able to circumvent that inline script checking which is recommended by FAB developer([`//We look at whether FuckAdBlock already exists`](https://github.com/sitexw/FuckAdBlock#code-example))

so that cases should be fixed by other rules.
for example, 
`tvserial.it#%#//scriptlet('set-constant', 'blockAdBlock', 'null')`
`123link.biz#%#//scriptlet('set-constant', 'blockAdBlock', 'undefined')`
