### ISSUE TITLE
Fix 'set-attr' — scriptlet does not work as it should

### ISSUE THREAD

**Issue by berkant** [AdguardTeam/Scriptlets#442]
So, here's the user rules:
```adb
example.com#%#//scriptlet('trusted-set-attr', 'body', 'test-attr1', 'test-val1')
example.com#%#//scriptlet('set-attr', 'body', 'test-attr2', 'test-val2')
```

Result:
![image](https://github.com/user-attachments/assets/eacdb30e-cbbb-40a4-9a9c-3f7121588d97)

Plus, `trusted-set-attr` doesn't seem to support using the attribute name as a means to concat:
```adb
example.com#%#//scriptlet('trusted-set-attr', 'body', 'test-attr3', '[test-attr1] test-attr3')
```

Result:
![image](https://github.com/user-attachments/assets/758a7164-b773-46fc-b3ef-b3d13da162d0)

**Comment by jellizaveta** [comment]
@berkant Hello. If I've understood you correctly, it seems that in your example:
```
example.com#%#//scriptlet('set-attr', 'body', 'test-attr2', 'test-val2')
```
 the attribute value is not set because `set-attr` [does not support](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-scriptlets.md#%EF%B8%8F-set-attr) custom values.

Unfortunately, I don't understand this example, could you please describe it in more detail:
```
example.com#%#//scriptlet('trusted-set-attr', 'body', 'test-attr3', '[test-attr1] test-attr3')
```
4 parameter in [trusted-set-attr](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-trusted-scriptlets.md#-%EF%B8%8F-trusted-set-attr) is the attribute value
